### ISSUE TITLE
Trying to just extract the mantissa, exponent, and sign

### ISSUE THREAD

**Issue by vinniefalco** [ulfjack/ryu#108]
I'm trying to extract
```
unsigned long long mantissa;
short exponent;
bool negative;
```
from a `double`. I already wrote some code before I heard about the Ryū so if anyone reading this wants a good laugh here it is:
```
    if(f < 0)
    {
        f = std::abs(f);
        neg_ = true;
    }
    else
    {
        neg_ = false;
    }
    static exponent_type const bias =
        static_cast<exponent_type>(std::floor(
            std::log10((std::numeric_limits<
                mantissa_type>::max)()))) - 2;
    exp_ = static_cast<exponent_type>(
        std::floor(std::log10(f)));
    auto mant = f / std::pow(10, exp_);
    mant_ = static_cast<mantissa_type>(
        mant * std::pow(10, bias));
    exp_ -= bias;
```

It is considerably simpler than Ryū and correspondingly, less correct.

I'm trying to adapt the source code in this project to achieve my ends, but it seems to be very oriented towards printing rather than simple extraction of the decimal mantissa and exponent, am I missing something? What's the shortest path to getting these numbers?

**Comment by StephanTLavavej** [comment]
(Extracting the sign is trivial; it's the most significant bit, which you can then mask away.)

I think you want this:

https://github.com/ulfjack/ryu/blob/41910f966fdc2307a279ef645de976e0fc431b48/ryu/d2s.c#L205-L211

This is what the code calls after special-casing NAN/INF/zero, before printing characters. Given the double that can be written in source code as an exact hexfloat `0x1.14a3d70a3d70ap+4` or an exact decimal `17.28999999999999914734871708787977695465087890625` or an inexact decimal `17.29`, it will determine that the shortest round-trip decimal is 1729 * 10^-2, and return a `floating_decimal_64` containing `1729` and `-2` (which can be emitted with a bit of work as scientific notation, or with much more work as fixed notation).

Note that Ryu generates the shortest round-trip decimal mantissa and exponent. This is very useful (in particular, it preserves all of the information that was in the 64-bit double, by definition), as long as you understand what it's doing. Large exactly-representable integers (including but not limited to powers of 2) will be rounded to something with lots of 0s in this process.
