### ISSUE TITLE
Does this work on all platforms?

### ISSUE THREAD

**Issue by vinniefalco** [ulfjack/ryu#112]
What happens if `std::numeric_limits<double>::is_iec559()` returns false?

**Comment by StephanTLavavej** [comment]
The C++ Standard specifies `is_iec559` as "`true` if and only if the type adheres to ISO/IEC/IEEE 60559" and helpfully notes that "ISO/IEC/IEEE 60559:2011 is the same as IEEE 754-2008".

Ryu's implementation assumes that 32-bit floats and 64-bit doubles have IEEE-754 representations (in particular, how many bits are allocated to exponent vs. mantissa). Are you aware of platforms where this isn't true? (For example, it is true for all Microsoft platforms.)

**Comment by vinniefalco** [comment]
Personally, I do not know of any platforms that use other representations, and my desire to support such platforms is minimal to say the least. However, a certain nameless individual exclaimed:

> Of course some people running code on IBM mainframes might object. And I know that the IBM compiler people support boost.

Hence the question. Thanks!
