### ISSUE TITLE
The tests leak

### ISSUE THREAD

**Issue by vinniefalco** [ulfjack/ryu#121]
Memory allocated by routines such as `f2s` is never freed. When the tests are run under a sanitizer, leaks are reported.

**Comment by ulfjack** [comment]
I was able to reproduce on MacOS with:
```
leaks --atExit -- ../../bazel-bin/ryu/tests/f2s_test
```

It's a bit awkward to free the memory, but I suppose we can do that with another layer of macros?

**Comment by ulfjack** [comment]
Also, it's possible to run tests in the leak checker with bazel like so:
```
bazel test --run_under="leaks --atExit -- " :d2s_test
```

**Comment by ulfjack** [comment]
All the tests now pass with the leak checker enabled.

**Comment by vinniefalco** [comment]
I used a different technique...LOL
```
char* d2s(double f) noexcept
{
    static thread_local char result[25];
    d2s_buffered(f, result);
    return result;
}
```

**Comment by ulfjack** [comment]
Yeah, I considered using a static buffer but decided against it.

**Comment by vinniefalco** [comment]
These routines aren't public so really I'm only using them for the tests
