### ISSUE TITLE
Hello. What does POW10_SPLIT mean?

### ISSUE THREAD

**Issue by expnkx** [ulfjack/ryu#125]
Thank you so much!

**Comment by expnkx** [comment]
https://github.com/ulfjack/ryu/blob/master/ryu/d2fixed.c#L715

By the way, what are the differences between c,d,n,nine in append_x_digits?
append_c_digits
append_d_digits
append_n_digits
append_nine_digits

**Comment by expnkx** [comment]
Also, is fixed mode only working for double??

**Comment by ulfjack** [comment]
The POW10_SPLIT table is a table of powers of 10, the top few bits, split into machine-size integers.

There's no particular meaning for the c/d/n letters. They should probably be renamed for clarity.

Wrt. fixed mode: casting a float to a double is loss-less, and fixed-mode does not take the width of the input into account. As such, you can just use the existing method. The only reason for providing a specialized method for float would be performance - presumably, we could do the conversion faster if the input is smaller. #102 is the corresponding feature request.

**Comment by expnkx** [comment]
> The POW10_SPLIT table is a table of powers of 10, the top few bits, split into machine-size integers.
> 
> There's no particular meaning for the c/d/n letters. They should probably be renamed for clarity.
> 
> Wrt. fixed mode: casting a float to a double is loss-less, and fixed-mode does not take the width of the input into account. As such, you can just use the existing method. The only reason for providing a specialized method for float would be performance - presumably, we could do the conversion faster if the input is smaller. #102 is the corresponding feature request.

But my question is for long double. How to output long double?

**Comment by ulfjack** [comment]
That's not implemented yet.

**Comment by expnkx** [comment]
> That's not implemented yet.

Hello.  I think these tables can be generated by C++ 14/17 at compilation time through constexpr. Can you provide your source code for generating these tables?

**Comment by ulfjack** [comment]
The printf tables are generated here:
https://github.com/ulfjack/ryu/blob/master/src/main/java/info/adams/ryu/printf/PrintPrintfLookupTable.java

The shortest conversion tables are generated here:
https://github.com/ulfjack/ryu/blob/master/src/main/java/info/adams/ryu/analysis/PrintDoubleLookupTable.java

If you find a way to do that with constexpr, I'll be very impressed.
