### ISSUE TITLE
Is this correct? 39354.2857386751165905 scientific 20 provides wrong answer while 3.93542857386751165905 is right.

### ISSUE THREAD

**Issue by expnkx** [ulfjack/ryu#127]
gcc 10.0

d2exp_buffered_n(3.93542857386751165905 ,20,arr.data())
3.93542857386751165905e+00
answer:

d2exp_buffered_n(39354.2857386751165905 ,20,arr.data())
answer: 3.93542857386751202284e+04

Why? Although I think your answer is valid (since double only holds valid 18 decimal).

**Comment by StephanTLavavej** [comment]
It is correct. The decimal value `39354.2857386751165905` isn't exactly representable as an IEEE 64-bit `double`. The nearest representable value is `39354.2857386751202284358441829681396484375`, which is what's actually stored in the `double`. Printing this in scientific notation with 20 digits of precision after the decimal point is then `"3.93542857386751202284e+04"` (the next digit would be `"3"`, so it's rounded down).

You can use `printf()` from the C Standard Library to explore this without the Ryu Printf algorithm. MSVC's UCRT or GNU glibc will behave identically here. MSVC:

```
C:\Temp>type meow.cpp
#include <stdio.h>

int main() {
    const double d = 39354.2857386751165905;
    printf("%.1000g\n", d);
    printf("%.20e\n", d);
}

C:\Temp>cl /EHsc /nologo /W4 meow.cpp
meow.cpp

C:\Temp>meow
39354.2857386751202284358441829681396484375
3.93542857386751202284e+04
```

GCC 9.2 on Godbolt's Compiler Explorer: https://godbolt.org/z/Bx36dE

(Note that `"%.1000g"` is an easy way to get the exact value of a `double`; it requests more decimal digits than any `double` can possibly have, then trims trailing zeros.)

**Comment by expnkx** [comment]
> It is correct. The decimal value `39354.2857386751165905` isn't exactly representable as an IEEE 64-bit `double`. The nearest representable value is `39354.2857386751202284358441829681396484375`, which is what's actually stored in the `double`. Printing this in scientific notation with 20 digits of precision after the decimal point is then `"3.93542857386751202284e+04"` (the next digit would be `"3"`, so it's rounded down).
> 
> You can use `printf()` from the C Standard Library to explore this without the Ryu Printf algorithm. MSVC's UCRT or GNU glibc will behave identically here. MSVC:
> 
> ```
> C:\Temp>type meow.cpp
> #include <stdio.h>
> 
> int main() {
>     const double d = 39354.2857386751165905;
>     printf("%.1000g\n", d);
>     printf("%.20e\n", d);
> }
> 
> C:\Temp>cl /EHsc /nologo /W4 meow.cpp
> meow.cpp
> 
> C:\Temp>meow
> 39354.2857386751202284358441829681396484375
> 3.93542857386751202284e+04
> ```
> 
> GCC 9.2 on Godbolt's Compiler Explorer: https://godbolt.org/z/Bx36dE
> 
> (Note that `"%.1000g"` is an easy way to get the exact value of a `double`; it requests more decimal digits than any `double` can possibly have, then trims trailing zeros.)

ok. another question. 

double d;
std::to_chars(arr.data(),arr.data()+arr.size(),d,std::chars_format::fixed);

How many precisions of this?

**Comment by StephanTLavavej** [comment]
That's off-topic for Ulf's repo (which currently doesn't have shortest fixed notation logic), but I can try to describe it. For integer values, it prints all of the digits to the left of the decimal point (via Ryu Printf or long division), and no decimal point or digits to the right (so, precision 0). That is, 2<sup>100</sup> is printed as `"1267650600228229401496703205376"` which is its exact value. For values with fractional parts, Ryu's scientific shortest output is adjusted to fixed notation by appropriately adding `'0'` digits. In scientific notation, Ryu emits at most 17 significant digits (16 digits of precision, after the decimal point) for `double`. In fixed notation, this can be preceded by a vast number of `'0'` digits (e.g. 2<sup>-100</sup> is going to have many). So the precision in terms of `printf()` `"%.*f"` may be a large number, but the effective precision is at most 17 significant digits.

I am actually unable to prove an exact bound for the longest output in shortest fixed notation. (The very smallest numbers have the most `'0'` digits, but require few significant digits to round-trip.) I can prove a somewhat loose upper bound, though.

**Comment by expnkx** [comment]
> That's off-topic for Ulf's repo (which currently doesn't have shortest fixed notation logic), but I can try to describe it. For integer values, it prints all of the digits to the left of the decimal point (via Ryu Printf or long division), and no decimal point or digits to the right (so, precision 0). That is, 2100 is printed as `"1267650600228229401496703205376"` which is its exact value. For values with fractional parts, Ryu's scientific shortest output is adjusted to fixed notation by appropriately adding `'0'` digits. In scientific notation, Ryu emits at most 17 significant digits (16 digits of precision, after the decimal point) for `double`. In fixed notation, this can be preceded by a vast number of `'0'` digits (e.g. 2-100 is going to have many). So the precision in terms of `printf()` `"%.*f"` may be a large number, but the effective precision is at most 17 significant digits.
> 
> I am actually unable to prove an exact bound for the longest output in shortest fixed notation. (The very smallest numbers have the most `'0'` digits, but require few significant digits to round-trip.) I can prove a somewhat loose upper bound, though.

Then why not try to ask him for implementing this?

**Comment by StephanTLavavej** [comment]
I implemented it in charconv (and my heavily mutated, not-standalone-compileable fork of ryu). Aside from a bit of cleverness when deciding when Ryu can be used directly, versus falling back to Ryu Printf, there’s no magic or novel algorithms - just really careful attention to boundary cases and counting characters. Contributing this back (in addition to bounds checking) is on my todo list.

**Comment by expnkx** [comment]
> I implemented it in charconv (and my heavily mutated, not-standalone-compileable fork of ryu). Aside from a bit of cleverness when deciding when Ryu can be used directly, versus falling back to Ryu Printf, there’s no magic or novel algorithms - just really careful attention to boundary cases and counting characters. Contributing this back (in addition to bounds checking) is on my todo list.

I don't know whether clang implements this. However, GCC does not.

TBH, I can easily beat charconv or ryu_source since I can do crazy optimization to buffer directly. That is a huge weakness for charconv. It does not talk with the buffer directly. That is why we desperately need a new io library to replace both stdio.h and iostream.

D:\hg\fast_io\examples\0021.benchmark>output_10M_double_scientific
ryu_source:     1.15696400s
obuf:   1.02800000s
obuf_mutex:     1.04000000s
speck128/128:   1.63399900s

D:\hg\fast_io\examples\0021.benchmark>output_10M_size_t
std::FILE*:     2.13056600s
std::ofstream:  1.27400100s
std::ofstream with tricks:      1.14300700s
std::to_chars + ofstream rdbuf tricks:  0.91224500s
std::to_chars + obuf:   0.12300600s
obuf:   0.07400400s
obuf text:      0.16897500s
obuf ucs_view:  0.16200000s
dynamic obuf:   0.12700400s
obuf_mutex:     0.13700300s
fsync:  0.32956400s
speck128/128:   0.27693600s

**Comment by expnkx** [comment]
> I implemented it in charconv (and my heavily mutated, not-standalone-compileable fork of ryu). Aside from a bit of cleverness when deciding when Ryu can be used directly, versus falling back to Ryu Printf, there’s no magic or novel algorithms - just really careful attention to boundary cases and counting characters. Contributing this back (in addition to bounds checking) is on my todo list.

However, this library
