### ISSUE TITLE
Why not just write this as C++ so you can use templates/if constexpr instead of writing different floating types over and over again

### ISSUE THREAD

**Issue by expnkx** [ulfjack/ryu#128]
Thank you for your algorithm and code. I have done fixed and scientific part of it based on your code and I don't see any performance lost and my code is even faster since it can deal with buffer.

**Comment by expnkx** [comment]
This is my implementation of fixed and scientific. I just feel too many code are just the same. I will finish the part of shortest this week.
https://github.com/expnkx/fast_io/blob/master/include/fast_io_freestanding_impl/ryu/fixed.h

Here are some benchmarks you could use for testing.
https://github.com/expnkx/fast_io/blob/master/examples/0021.benchmark/output_10M_double.cc
https://github.com/expnkx/fast_io/blob/master/examples/0021.benchmark/output_10M_double_with_charconv.cc

**Comment by expnkx** [comment]
Also, do you know how to do shortest scientific, fixed and hex?

**Comment by ulfjack** [comment]
By all means, feel free to port this to C++. C and C++ are often considered interchangeable, but sometimes they are not, so I don't see the harm in having two implementations.

**Comment by ulfjack** [comment]
I haven't looked into any of the formats you mention. I assume you mean "shortest fixed"? Hex shouldn't be hard (famous last words).

**Comment by expnkx** [comment]
> I haven't looked into any of the formats you mention. I assume you mean "shortest fixed"? Hex shouldn't be hard (famous last words).

Yea. Not shortest fixed. shortest fixed and scientific mixed. If a number could output fixed for shorter length, use fixed, or it will use scientific. The algorithm needs to make the decision by itself.

For example
This default:
0.000005 will use scientific shortest 5E-06
0.5 will use 0.5

I don't know whether hex with precision would be hard (since it has round issues as well). The problem is that charconv is a huge crap that requires the library implementation to implement something which is currently not possible.

**Comment by ulfjack** [comment]
Can you point me to the specification? Does it define the length in number of output characters?

**Comment by expnkx** [comment]
> By all means, feel free to port this to C++. C and C++ are often considered interchangeable, but sometimes they are not, so I don't see the harm in having two implementations.

The problem is that you are implementing multi-precision very hard with C since you are not using templates which is why a lot of stuff is not available (like long double fixed, long double scientific with precision)

When I implement your algorithm, what I first do is to write an unsigned extension which can easily be used for making uint128_t uint256_t.
https://github.com/expnkx/fast_io/blob/master/include/fast_io_core_impl/unsigned_extension.h

**Comment by expnkx** [comment]
> Can you point me to the specification? Does it define the length in number of output characters?

Yes!

**Comment by expnkx** [comment]
Try to output the shortest round-trip floating-point for fixed and scientific. Compare their length. Get the shorter one :)

**Comment by verelpode** [comment]
Although I switched from C++ to C# some years ago, I agree that @expnkx is making a very good point.   What's impressive about the current version of Ryu is the algorithmic aspects and the fundamentals, but **not** the plain-C source code.  Unfortunately Ryu's plain-C source code is lagging far behind modern programming practices.  To give honest feedback, unfortunately I have to say that it's like taking a trip back in time to the beginning of my career decades ago.   

Nevertheless I'm still very impressed with the work of @ulfjack, and I see that he accomplished things that I don't have the ability to do.  Overall Ryu is great stuff.   The downside is just that the provided implementation uses a very outdated choice of programming language and style, but more importantly this newly invented algorithm is great.

**Comment by ulfjack** [comment]
I'm not planning to have a C++ version in this repository, but happy to link to one.
