### ISSUE TITLE
ryu shortest shortest

### ISSUE THREAD

**Issue by expnkx** [ulfjack/ryu#130]
Hi ulfjack. Here is the formula I get from math myself. Is this a correct and valid definition?

https://github.com/expnkx/fast_io/blob/master/include/fast_io_freestanding_impl/ryu/fixed.h#L761

		std::uint32_t fixed_length(0),this_case(0);
		if(olength<real_exp)
		{
			fixed_length=real_exp+1;
			this_case=1;
		}
		else if(0<=real_exp&&real_exp<olength)
		{
			fixed_length=olength+2;
			if(olength==real_exp+1)
				--fixed_length;
			this_case=2;
		}
		else
			fixed_length=static_cast<exponent_type>(-real_exp)+olength+1;
		std::uint32_t scientific_length(olength==1?olength+3:olength+5);
		if(scientific_length<fixed_length)
		{
			output_base_number_impl<10,false,true>(result+=olength+1,v.front());
			return output_exp<uppercase_e>(static_cast<std::int32_t>(real_exp),result);
		}

**Comment by ulfjack** [comment]
I'm not sure what that code is trying to do. What's the math you got the formula from?

**Comment by expnkx** [comment]
> I'm not sure what that code is trying to do. What's the math you got the formula from?

Well. There are shortest fixed, shortest scientific and shortest shortest by the C++ standard library charconv.

if your just by default output a double, it should be a fixed mode. Pick the shortest shortest one.

I just use your result (since it is scientific representation of floating point), try to use that result to calculate fixed and scientific which is shorter before making the decision which to output.

I discuss the relationship between exponent and number length, I think this can make the correct decision.

**Comment by expnkx** [comment]
> I'm not sure what that code is trying to do. What's the math you got the formula from?

If you could finish all parts of this amazing algorithm, I will submit this algorithm to GCC.

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/69004683-6dbf2d80-08e5-11ea-81f1-edebecee6f3b.png)
Thank you for your amazing algorithm
