### ISSUE TITLE
question about ryu_parse. incorrect input???

### ISSUE THREAD

**Issue by expnkx** [ulfjack/ryu#133]
#include"ryu_parse.h"
#include<stdio.h>

int main()
{
	printf("here:%f",s2d("1.453"));
}

D:\git\ryu\ryu>g
Input=1.453
m10 * 10^e10 = 1453 * 10^-3
m2 * 2^e2 = 3047161 * 2^-21
ieee_e2 = 1055
shift = 1
here:4294967297.453000
![image](https://user-images.githubusercontent.com/57303909/69492357-e8e98c00-0e6f-11ea-902b-4f7b14734947.png)

Here is my implementation, probably can help you:

https://bitbucket.org/ejsvifq_mabmip/fast_io/src/default/include/fast_io_freestanding_impl/ryu/id.h

My implementation gives the correct answer for 1.453
![image](https://user-images.githubusercontent.com/57303909/69492340-a88a0e00-0e6f-11ea-901e-d37ce251c91a.png)

However, when I gives XXXe2, it becomes wrong, why? 

![image](https://user-images.githubusercontent.com/57303909/69492366-0f0f2c00-0e70-11ea-8119-519ec9fb18cc.png)
https://bitbucket.org/ejsvifq_mabmip/fast_io/src/default/examples/0009.floating%20point/s2d.cc

**Comment by expnkx** [comment]
I have found out the reason why 2e2 for my implementation fails since I mess up the exponent.

**Comment by ulfjack** [comment]
Sorry, I keep messing up my constants. I used ```1L``` instead of ```1ull```. Fixed on the branch.

**Comment by expnkx** [comment]
> Sorry, I keep messing up my constants. I used `1L` instead of `1ull`. Fixed on the branch.

Another problem I found:

I think it should be "__builtin_clzll" not "__builtin_clzl"

**Comment by expnkx** [comment]
Should be this:
static inline uint32_t floor_log2(const uint64_t value) {
  return 63 - __builtin_clzll(value);
}

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/69493112-b1331200-0e78-11ea-9b5b-f3235ec3d854.png)

**Comment by ulfjack** [comment]
Duh.
