### ISSUE TITLE
I think it is an interesting question which could go further. Any base parsing????

### ISSUE THREAD

**Issue by expnkx** [ulfjack/ryu#141]
Any possibility of supporting any base (from base 2- base36) for floating-point?

For example, base 36's shortest, scientific, fixed, precision shortest, precision scientific, precision fixed and parsing base 36 string to floating.

THAT WOULD BE AWESOME.

**Comment by ulfjack** [comment]
It is technically possible, but I have no intention to work on this any time soon.
