### ISSUE TITLE
Remove trailing zeros from output functions

### ISSUE THREAD

**Issue by Algunenano** [ulfjack/ryu#142]
Hi, first of all thanks a lot for the library, it's performance is really awesome. 

I've been working in integrating it in [Postgis](http://postgis.net/) which decides the format and the amount of decimal digits to print depending on multiple parameters (user input and space left in the buffer), so I can't use `d2s_buffered_n`.

My main issue is that both `d2fixed_buffered_n` and `d2exp_buffered_n` include trailing zeros, like  `15.0000` or `2.010e+04`. Although it is possible to remove them manually by looking for `.` or `e`, it isn't very efficient; since ryu already knows about what's trailing and what not, I'd modified it to remove them if required.

I was wondering if it makes sense to contribute this here. If so, I would create a PR and make any necessary changes to have this included.

In case you want to have a look, the current patch looks like this:
```diff
diff --git a/ryu/d2fixed.c b/ryu/d2fixed.c
index b008dab..3bcc22f 100644
--- a/ryu/d2fixed.c
+++ b/ryu/d2fixed.c
@@ -420,7 +420,8 @@ int d2fixed_buffered_n(double d, uint32_t precision, char* result) {
   if (!nonzero) {
     result[index++] = '0';
   }
-  if (precision > 0) {
+  const bool printDecimalPoint = precision > 0;
+  if (printDecimalPoint) {
     result[index++] = '.';
   }
 #ifdef RYU_DEBUG
@@ -532,6 +533,18 @@ int d2fixed_buffered_n(double d, uint32_t precision, char* result) {
     memset(result + index, '0', precision);
     index += precision;
   }
+
+#if RYU_NO_TRAILING_ZEROS
+  if (printDecimalPoint) {
+    while (result[index - 1] == '0') {
+      index--;
+    }
+    if (result[index - 1] == '.') {
+      index--;
+    }
+  }
+#endif
+
   return index;
 }
 
@@ -771,6 +784,18 @@ int d2exp_buffered_n(double d, uint32_t precision, char* result) {
       }
     }
   }
+
+#if RYU_NO_TRAILING_ZEROS
+  if (printDecimalPoint) {
+    while (result[index - 1] == '0') {
+      index--;
+    }
+    if (result[index - 1] == '.') {
+      index--;
+    }
+  }
+#endif
+
   result[index++] = 'e';
   if (exp < 0) {
     result[index++] = '-';
```
It only does the extra checks when `RYU_NO_TRAILING_ZEROS` is defined, so the performance for the current case shouldn't be affected.

**Comment by expnkx** [comment]
No. You fail to understand what is precision fixed/precision exp. These zeros after 0.010 are required in as results.


https://github.com/expnkx/fast_io/blob/master/include/fast_io_freestanding_impl/ryu/fixed.h
You better just use the shortest and let the algorithm decides which form to use.

https://github.com/expnkx/fast_io/blob/master/examples/0009.floating%20point/double_default.cc

**Comment by Algunenano** [comment]
> No. You fail to understand what is precision fixed/precision exp. These zeros after 0.010 are required in as results. 0 cannot be ignored.

Can you explain why?

Here is a simple example:
```c
    static const double d = 0.5;

    for (int i = 1; i < 64; i++)
    {
        char ds[128] = {0};
        size_t len = d2fixed_buffered_n(d, i, ds);
        ds[len] = '\0';
        printf("Ryu %d: %s\n", i, ds);
    }
```

The output will look something like:
```
Ryu 1: 0.5
Ryu 2: 0.50
Ryu 3: 0.500
Ryu 4: 0.5000
Ryu 5: 0.50000
Ryu 6: 0.500000
```

Why would I want all the extra zeros output there? Am I missing something?

> You better just use the shortest and let the algorithm decides which form to use.

When that means breaking 10+ years of output and API, I don't think so.

**Comment by expnkx** [comment]
> > No. You fail to understand what is precision fixed/precision exp. These zeros after 0.010 are required in as results. 0 cannot be ignored.
> 
> Can you explain why?
> 
> Here is a simple example:
> 
> ```c
>     static const double d = 0.5;
> 
>     for (int i = 1; i < 64; i++)
>     {
>         char ds[128] = {0};
>         size_t len = d2fixed_buffered_n(d, i, ds);
>         ds[len] = '\0';
>         printf("Ryu %d: %s\n", i, ds);
>     }
> ```
> 
> The output will look something like:
> 
> ```
> Ryu 1: 0.5
> Ryu 2: 0.50
> Ryu 3: 0.500
> Ryu 4: 0.5000
> Ryu 5: 0.50000
> Ryu 6: 0.500000
> ```
> 
> Why would I want all the extra zeros output there? Am I missing something?
> 
> > You better just use the shortest and let the algorithm decides which form to use.
> 
> When that means breaking 10+ years of output and API, I don't think so.

Same with stdio.h or iostream. That is exactly what the result of the fixed_precision API should provide because you, as users, require precisions here.

#include<iostream>
#include<iomanip>

int main()
{
    double d = 0.5;
    std::cout<<std::fixed;
    for (int i = 1; i < 64; ++i)
    {
       std::cout<<"stream "<<i<<": "<<std::setprecision(i)<<d<<'\n';
    }
}

$ ./wc
stream 1: 0.5
stream 2: 0.50
stream 3: 0.500
stream 4: 0.5000
stream 5: 0.50000
stream 6: 0.500000
....

I think you should probably use my fast_io library for doing this since I do more than ryu does if you want ryu shortest fixed/scientific/shortest.

https://github.com/expnkx/fast_io/blob/master/examples/0009.floating%20point/zerop5.cc

**Comment by expnkx** [comment]
You need to download the latest GCC from here if you wanna use my library.

https://bitbucket.org/ejsvifq_mabmip/mingw-gcc/src/master/

**Comment by expnkx** [comment]
https://github.com/expnkx/fast_io/blob/master/include/fast_io_freestanding_impl/ryu/fixed.h
Line 813+
Here is my code to deal with it. However, you need at least c++17 compiler to support if constexpr
```cpp
	std::int32_t olength(static_cast<std::int32_t>(chars_len<10,true>(v.front())));
	std::int32_t const real_exp(static_cast<std::int32_t>(e10 + removed + olength - 1));
	if constexpr(mode==0) //shortest
	{
		std::uint32_t fixed_length(0),this_case(0);
		if(olength<=real_exp)
		{
			fixed_length=real_exp+1;
			this_case=1;
		}
		else if(0<=real_exp&&real_exp<olength)
		{
			fixed_length=olength+2;
			if(olength==real_exp+1)
				--fixed_length;
			this_case=2;
		}
		else
			fixed_length=static_cast<exponent_type>(-real_exp)+olength+1;
		std::uint32_t scientific_length(olength==1?olength+3:olength+5);
		if(scientific_length<fixed_length)
		{
			if(olength==1)
				output_base_number_impl<10,false,false>(result+=olength,v.front());
			else
				output_base_number_impl<10,false,true>(result+=olength+1,v.front());
			return output_exp<uppercase_e>(static_cast<std::int32_t>(real_exp),result);
		}
		switch(this_case)
		{
		case 1:
			output_base_number_impl<10,false>(result+=olength,v.front());
			return my_fill_n(result,real_exp+1-olength,0x30);
		case 2:
		{
			constexpr auto &table(details::shared_static_base_table<10,uppercase_e>::table);
			constexpr std::uint32_t pw(table.size());
			constexpr std::uint32_t chars(table.front().size());
			auto a(v.front());
			auto eposition(result+real_exp+1);
			auto iter(result+=olength);
			if(eposition!=iter)
			{
				++result;
				++iter;
				for(;eposition+2<iter&&pw<=a;)
				{
					auto const rem(a%pw);
					a/=pw;
					my_copy_n(table[rem].data(),chars,iter-=chars);
				}
				if(iter==eposition+2)
				{
					auto const rem(a%10);
					a/=10;
					*--iter=static_cast<char_type>(0x30+rem);
				}
				*--iter=0x2E;
			}
			output_base_number_impl<10,false>(iter,a);
			return result;
		}
		default:
			result=my_copy_n(u8"0.",2,result);
			result=my_fill_n(result,static_cast<exponent_type>(-real_exp-1),0x30);
			output_base_number_impl<10,false>(result+=olength,v.front());
			return result;
		}
	}
	else if constexpr(mode==1) //fixed
	{
		if(olength<=real_exp)
		{
			output_base_number_impl<10,false>(result+=olength,v.front());
			return my_fill_n(result,real_exp+1-olength,0x30);	
		}
		else if(0<=real_exp&&real_exp<olength)
		{
			constexpr auto &table(details::shared_static_base_table<10,uppercase_e>::table);
			constexpr std::uint32_t pw(table.size());
			constexpr std::uint32_t chars(table.front().size());
			auto a(v.front());
			auto eposition(result+real_exp+1);
			auto iter(result+=olength);
			if(eposition!=iter)
			{
				++result;
				++iter;
				for(;eposition+2<iter&&pw<=a;)
				{
					auto const rem(a%pw);
					a/=pw;
					my_copy_n(table[rem].data(),chars,iter-=chars);
				}
				if(iter==eposition+2)
				{
					auto const rem(a%10);
					a/=10;
					*--iter=static_cast<char_type>(0x30+rem);
				}
				*--iter=0x2E;
			}
			output_base_number_impl<10,false>(iter,a);
			return result;
		}
		else
		{
			result=my_copy_n(u8"0.",2,result);
			result=my_fill_n(result,static_cast<exponent_type>(-real_exp-1),0x30);
			output_base_number_impl<10,false>(result+=olength,v.front());
			return result;
		}
	}
	else		//scientific
	{
		if(olength==1)
			output_base_number_impl<10,false,false>(result+=olength,v.front());
		else
			output_base_number_impl<10,false,true>(result+=olength+1,v.front());
		return output_exp<uppercase_e>(static_cast<std::int32_t>(real_exp),result);
	}
```
