### ISSUE TITLE
Hi, I implemented a Ryu algorithm using C#.

### ISSUE THREAD

**Issue by Dogwei** [ulfjack/ryu#145]
Your algorithm is so good!

[https://github.com/Dogwei/RyuCsharp](https://github.com/Dogwei/RyuCsharp)

This project is translated from c implementation.

I just change the syntax and i don't change the logic.

**Comment by expnkx** [comment]
I have implemented more like shortest shortest (I think it is the most useful stuff for integer to string conversion). You probably need them as well.
ryu source is C based so I couldn't contribute my code.

https://bitbucket.org/ejsvifq_mabmip/fast_io/src/master/include/fast_io_freestanding_impl/ryu/fixed.h
https://bitbucket.org/ejsvifq_mabmip/fast_io/src/master/include/fast_io_freestanding_impl/ryu/id.h

**Comment by ulfjack** [comment]
Thanks! I added the C# implementation to the list in the README.
