### ISSUE TITLE
Thread safe?

### ISSUE THREAD

**Issue by oschonrock** [ulfjack/ryu#152]
I can't see any obvious shared mutable state. How confident are we that it is fully thread safe?

**Comment by StephanTLavavej** [comment]
I extensively reviewed most of Ulf’s code (the 32-bit and 64-bit flavors, but not generic_128 or Java) while adapting it for MSVC’s C++ Standard Library, and found no thread safety issues (e.g. modifiable global variables or function-static variables).

**Comment by ulfjack** [comment]
The code is fully threadsafe.
