### ISSUE TITLE
Clarify in what sense is ryu output the shortest

### ISSUE THREAD

**Issue by mikekaganski** [ulfjack/ryu#154]
For double d = 3.0, the expected shortest output is "3"; d2s (from release v2.0) generates "3E0".
For double d = 0.3, the expected shortest output is "0.3"; d2s generates "3E-1".

The implementation of [to_chars](https://github.com/ulfjack/ryu/blob/d4114cedf9de3a9504e0fc21e212ef1043af64c7/ryu/d2s.c#L314) doesn't seem to ever skip adding exponent. So d2s seems to be "the shortest possible variant of printf with %e"? Or do I misunderstand it?

**Comment by ulfjack** [comment]
The output is shortest in the sense that it has the fewest number of decimal digits. The paper contains a definition. For the actual output, I decided to match previous implementations (Grisu) char-by-char. ryu_generic_128.h provides a low-level API that returns a decimal fraction (with the fewest number of decimal digits), and which allows you to use whatever formatting you want.

**Comment by mikekaganski** [comment]
Thanks; the confusion comes from the home page (https://github.com/ulfjack/ryu), which tells:

> For example, consider the binary 32-bit floating point number ... this floating point number is also the closest number to the decimal number 0.3, so that is what Ryu outputs

which creates impression that the expected output includes strings like "0.3".

**Comment by newbie-02** [comment]
hello @mikekaganski, evtl. you may find an appr. solution in issue #211... be careful, thinking about I'm a little unsure if it will change some exceptionals to '0' ...
