### ISSUE TITLE
Installation as submodule

### ISSUE THREAD

**Issue by arn4** [ulfjack/ryu#155]
Hi!
I'd like to install this project in as submodule of another git repo, but I don't understand how to properly include files. I'm using the C version of Ryu. I've cloned this repo in mine, in the fodder
`ryu_lib`. Now in my file `main.cc` I use the following line:
`#include "ryu_lib/ryu/d2fixed.c"`
but it does not compile since in that file, there's 
`#include "ryu/ryu.h"`
and the file does not exists. 
The only solution I found is a symbolic link to itself in the folder `ryu_lib/ryu` but I know that it's not a good idea and requires me to modify the repo, I don't want do that. 
How can I use the library properly, cloning it as submodule?

**Comment by ulfjack** [comment]
What are you using to build it? If you are using Bazel, I think it might work if you include it as a 'remote' workspace, e.g., by adding something like this to your WORKSPACE file:
```
local_repository(name = "ryu", path = "ryu_lib")
```

If you're using something else, you probably need to add ```ryu_lib``` to the include search path for your C/C++ compiler invocations, something like ```-Iryu_lib```.
