### ISSUE TITLE
FLOAT_POW5_INV_SPLIT table is too small for s2f

### ISSUE THREAD

**Issue by abolz** [ulfjack/ryu#164]
Since the introduction of `s2f`, the `FLOAT_POW5_INV_SPLIT` table has too few entries. (The table needs 55 entries, since we might need to multiply by 10^-54.)

Additionally, it would be nice if you could add the `RYU_FLOAT_FULL_TABLE` configuration to CI.

**Comment by ulfjack** [comment]
Sorry that last part is unclear to me. Add what to CI? (CI is configured through the checked-in `.travis.yml`.)

**Comment by abolz** [comment]
I meant testing the `RYU_FLOAT_FULL_TABLE` configuration on Travis (Like the `RYU_OPTIMIZE_SIZE` and `RYU_ONLY_64_BIT_OPS` configurations, which are already tested). I.e. adding another "bazel test ..." command to `.travis.yml`.

**Comment by ulfjack** [comment]
Is that what you had in mind?

I've also updated the settings to prevent merging changes that don't pass CI.

**Comment by abolz** [comment]
Yes, exactly! That's great!
