### ISSUE TITLE
Denormal boundary in parse

### ISSUE THREAD

**Issue by afrb2** [ulfjack/ryu#173]
Hi,

Noticed parsing (as double) 2.250738585072013e-308 which I'd expect to be normalized at the boundary i.e. zero normalized mantissa and exponent of 1

s2d found an exponent of 0 and a mantissa of 2^52 which clearly got masked down to 0 and returned zero which is suboptimal as there are many closer denormals!

One digit larger in last place worked viz 2.250738585072014e-308

**Comment by ulfjack** [comment]
I'm unable to reproduce. Which commit are you on? Can you try with HEAD?

**Comment by afrb2** [comment]
Yes, was using trunk - but I seem to have hit delete and lost a 2 from that number for which I apologise! 

Here is a simple test case with the correct number:


#include <string>
#include <iostream>

#include "ryu/ryu_parse.h"
#include <string>
#include <iostream>

#include "ryu/ryu_parse.h"

int main()
{
	std::string testCase = "2.2250738585072013e-308";

	double result;
	double ref = 2.2250738585072013e-308;
	Status st = s2d(testCase.c_str(), &result);

	if (st != SUCCESS)
	{
		std::cout << "Error";
	}

	if (result != ref)
	{
		std::cout << ref << " " << result << std::endl;
	}

}

Prints
2.22507e-308 0

**Comment by abolz** [comment]
@afrb2 The very same bug has recently been fixed for the `s2f` implementation (see 5fcc3418cb712085d70d85fda1a5c41301e148cf). The fix (with only minor modifications) should also be applicable to the `s2d` implementation. If you have some time to spare, it would be very nice if you could prepare and submit a PR. I think @ulfjack would probably happily accept the PR.

**Comment by afrb2** [comment]
Thanks!

Here is my attempt at a patch, I didn't seem to have permissions for a PR

From d17c478679bb1e1721cdc6c7ce25a8f9e1492698 Mon Sep 17 00:00:00 2001
From: Alan Bain <alan.bain@gmail.com>
Date: Tue, 30 Jun 2020 19:04:28 +0100
Subject: [PATCH] Proposed fix to avoid rounding mantissa down to zero for
 number on the denormal boundary and add test cases.

Signed-off-by: Alan Bain <alan.bain@gmail.com>
---
 ryu/s2d.c             | 6 ++++--
 ryu/tests/s2d_test.cc | 7 +++++++
 2 files changed, 11 insertions(+), 2 deletions(-)

diff --git a/ryu/s2d.c b/ryu/s2d.c
index e50c8bc..1486910 100644
--- a/ryu/s2d.c
+++ b/ryu/s2d.c
@@ -246,11 +246,13 @@ enum Status s2d_n(const char * buffer, const int len, double * result) {
   printf("ieee_m2 = %" PRIu64 "\n", (m2 >> shift) + roundUp);
 #endif
   uint64_t ieee_m2 = (m2 >> shift) + roundUp;
-  if (ieee_m2 == (1ull << (DOUBLE_MANTISSA_BITS + 1))) {
+  assert(ieee_m2 <= (1ull << (DOUBLE_MANTISSA_BITS + 1)));
+  ieee_m2 &= (1ull << DOUBLE_MANTISSA_BITS) - 1;
+  if (ieee_m2 == 0 && roundUp) {
     // Due to how the IEEE represents +/-Infinity, we don't need to check for overflow here.
     ieee_e2++;
   }
-  ieee_m2 &= (1ull << DOUBLE_MANTISSA_BITS) - 1;
+  
   uint64_t ieee = (((((uint64_t) signedM) << DOUBLE_EXPONENT_BITS) | (uint64_t)ieee_e2) << DOUBLE_MANTISSA_BITS) | ieee_m2;
   *result = int64Bits2Double(ieee);
   return SUCCESS;
diff --git a/ryu/tests/s2d_test.cc b/ryu/tests/s2d_test.cc
index 2bf0e5e..01beebb 100644
--- a/ryu/tests/s2d_test.cc
+++ b/ryu/tests/s2d_test.cc
@@ -90,3 +90,10 @@ TEST(S2dTest, TableSizeDenormal) {
 TEST(S2dTest, Issue157) {
   EXPECT_S2D(1.2999999999999999E+154, "1.2999999999999999E+154");
 }
+
+TEST(S2dTest, Issue173) {
+	// Denormal boundary
+	EXPECT_S2D(2.2250738585072012e-308, "2.2250738585072012e-308");
+	EXPECT_S2D(2.2250738585072013e-308, "2.2250738585072013e-308");
+	EXPECT_S2D(2.2250738585072014e-308, "2.2250738585072014e-308");
+}
\ No newline at end of file
--

**Comment by ulfjack** [comment]
Thanks! I applied your patch and pushed it to master.
