### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by jrahlf** [ulfjack/ryu#201]
- The link to https://github.com/expnkx/fast_io in the top level readme is dead.
- Documentation in ryu_parse.h says that `RYU_OPTIMIZE_SIZE` is not supported, but in `s2d.c` it actually uses the large or small lookup tables, depending on the existence of the define.

Is the string to float parsing still considered experimental? What features are possibly missing?

**Comment by ulfjack** [comment]
I have a plan for a parsing implementation that supports arbitrarily long inputs.
