### ISSUE TITLE
Add a prefix to exported names

### ISSUE THREAD

**Issue by chirsz-ever** [ulfjack/ryu#206]
It would be troublesome to export too simple names like `s2d`. `ryu_s2d` would be better.

**Comment by cppguru** [comment]
We are in violent agreement on that.  But that change could be unconditional.

**Comment by ecorm** [comment]
I've barked up that tree before https://github.com/ulfjack/ryu/issues/148

**Comment by cppguru** [comment]
@ecorm Hehe.  I read your motivation there.  Welcome to the club. :D

**Comment by cppguru** [comment]
But seriously those prefixes would be awesome.  I prefixed the stuff I added to our fork.

**Comment by ulfjack** [comment]
Closing as a dupe of #148.

**Comment by chirsz-ever** [comment]
> I've barked up that tree before #148

Sorry, it's my neglect.
