### ISSUE TITLE
question about ryu support in gcc? ( pure-'C' ) 

### ISSUE THREAD

**Issue by newbie-02** [ulfjack/ryu#209]
do I understand the comment from STL on std::to_chars https://github.com/ulfjack/ryu/issues/199#issuecomment-998406553 correctly that g++ and clang++ use ( can use ) ryu but 'pure-C' gcc does not have this option?  
if so, are there plans to implement that - and since here is not necessarily the right forum for that, where should you ask.

**Comment by ulfjack** [comment]
The code in this repository is pure C, but it doesn't implement the full `std::to_chars` standard. I'm generally happy to accept contributions, but I have very little time to work on it right now.
