### ISSUE TITLE
travis ci never completes its checks

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [ulfjack/ryu#219]
All PRs even from years ago have not completed.

**Comment by ulfjack** [comment]
Yeah, I'm aware :-(

**Comment by ulfjack** [comment]
It looks like Travis no longer offers free minutes for OSS projects. Will need to migrate to GH actions or some other solution.

**Comment by ulfjack** [comment]
Running Ubuntu and MacOS presubmit on GHA as of https://github.com/ulfjack/ryu/pull/226.
