### ISSUE TITLE
Big endian architectures?

### ISSUE THREAD

**Issue by ulfjack** [ulfjack/ryu#3]
The code that extracts the bits from a float, and the code that converts bits to a float probably don't work on big endian machines.

**Comment by mitchblank** [comment]
Are you sure?  The code claims:
```
// This only works on little-endian architectures.
```
...but looking at it it seems like it would probably work on any architecture where integer and floating point values are stored in the *same* endian.  That's not guaranteed to be true (and some machines in the past didn't have that) but it's a pretty safe bet today, especially for any machine that has IEEE754 floating point.

Basically, if the `double` was in X-endian then after the `memcpy()` onto a `uint64_t` it should still be readable in X-endian, no?

**Comment by ulfjack** [comment]
No idea. I don't have any big-endian machines available for testing. Of course, I'd be happy if the code just works. :-D

**Comment by mitchblank** [comment]
For comparison, it seems the double-conversion C++ library doesn't do anything special, besides documenting that integer-endianness and fp-endianness must be the same: https://github.com/google/double-conversion/blob/master/double-conversion/ieee.h#L35

I know that library works on big-endian hosts.

**Comment by mikkelfj** [comment]
I have not studied the code, but I have worked with grisu3 in FlatBuffers for C which does care about endianness.

Essentially the IEEE does not standardize on endianness, and as stated in an earlier comment, the general consensus is to byteswap floats on big endian platforms.

If considering the floating point value to be stored as bits embedded in a native uint64 encoding, then further bit processing will be platform neutral.

Note however that the actual cast from float to integer is highly sensitive to undefined C behavior, and is something I have had to address. You can see how grisu3 uses casts in the flatcc implementation. Essentially, the union cast approach is the most portable that I am aware of:

https://github.com/dvidelabs/flatcc/blob/ed32d6129fe1c6a00c7dec35f494aab5ac1f4c20/include/flatcc/portable/grisu3_math.h#L94-L123

Some older version of flatcc has been tested on big endian AIX machines so presumably grisu3 related JSON printing tests have passed as well, but there has been targeted grisu3 testing on big endian machines.

BTW: this library and algorithm is new to me. There are two issues with grisu3 - the one is the required fallback and the other is the lack of control over the printing resolution without slow post processing of rounded digits.

**Comment by mikkelfj** [comment]
The memcpy approach to float casting used in Ryu is probably the safest and most conservative approach to float casting, but likely also somewhat slower, especially on some platforms. I'd be interesting in hearing about a benchmark comparing the two approaches.

For reference, clang calls a block zero function when memsetting a trivial struct so it is faster to write zero fields in the struct directly. Presumably some compilers might be equally lazy with memcpy.

**Comment by mitchblank** [comment]
@mikkelfj -- In the past there were different tricks that worked best on different compilers: either the union trick, or by an naughty type-punning cast.  I still have code that has a mess of `#ifdef`s for this purpose.

However, using `memcpy()` is the only 100% portable method.  Happily, since gcc 4.9 and at least clang 3.0 the x86 compilers have been able to optimize the `memcpy()` call out perfectly.  Try for yourself: https://godbolt.org/g/SGLmBB

So I think these days it's best to just stick with `memcpy()` and trust the optimizer.

**Comment by mikkelfj** [comment]
Right, it works for recent clang x86 and interesting that it does - but MSVC 2017 does not impress, nor does icc 17, only icc 18 works optimally. (I can't test ARM with that tool).
 
Many users are constrained to specific compiler versions.

If you use unions you do not need ifdefs, since it practically works everywhere and even if you do, you can hide it behind static inlines in a dedicated header file.

https://godbolt.org/g/fcwKRh

Intrestingly the pointer version is faster in gcc 4.8, both with memcpy and union.

**Comment by ulfjack** [comment]
I added an implementation of the union-based conversion here:
https://github.com/ulfjack/ryu/pull/58

**Comment by mitchblank** [comment]
MSVC2017 actually does pretty good (not perfect) once you turn on optimization: https://godbolt.org/g/rdPtDv   In fact it gets the `from_pointer` variant correct on `memcpy()` but not on the union version.  For from_register it spills to the stack either way.

So at least for the latest versions of gcc/clang/msvc/icc `memcpy()` is not slower and in some cases slightly faster than union.

> If you use unions you do not need ifdefs, since it practically works everywhere

It is true that compilers are currently forgiving about type-punning through unions, even though it's not strictly correct according to the standard.  OTOH, it wasn't *that* long ago that we said the same thing about plain type-punning casts, but then optimizers caught up and things started breaking.

**Comment by ulfjack** [comment]
Yeah, I looked through godbolt, and most recent compilers seem to handle memcpy just fine. I have personally no idea of which constructs are portable and which are not, and I also understand that someone might want to eek the last bit of performance out of some less widely used compiler.

Unless someone makes a strong case, I'd prefer not to merge #58, or only merge the part where I'm moving it to a separate method (might want that to support a lower-level conversion API), but drop the union-based implementation.

I'll also update the docs to mention that the code requires int and float to be the same endianness to close out this issue.

**Comment by mikkelfj** [comment]
I think it is fine to keep memcpy knowing what we know now. It is simpler than unions.

It is fair to expect portable and decent performance on most compilers but it is fair to require a recent compiler to get the best possible performance.

**Comment by ulfjack** [comment]
Documented in cbb028519c33da2ffd33dd6ee646ebd579471ea0. Comments still need to be updated.

**Comment by mikkelfj** [comment]
For the sake of platforms that might have an issue with memcpy, it would be helpful to keep the inlines as you suggested. A project then only need to modify those functions with a patch rather than hunting down all occurrences.
