### ISSUE TITLE
Would a smarter decimalLength() help?

### ISSUE THREAD

**Issue by mitchblank** [ulfjack/ryu#34]
The current `decimalLength()` code is just a series of `if()` statements.  Since the value is usually near the top of the range this isn't *so* bad (i.e. it's not common to get far down list of `if()` statements)  However, it's going to compile down to a pretty large number of instructions and at least the first branch is going to predict pretty badly.

On platforms that have a "number-of-leading-zeros" instruction (including x86_64) there is simple branch-free method of computing  an integer`log10()` (with the caveat that an input of `0` needs to be treated as a special case when using that to computing "number of digits")  This isn't my gist, but here's the first one that popped up when I googled: https://gist.github.com/CAFxX/ad150f2403a0604e14cc   There are also variants that do a couple more ALU instructions to shrink the thr[] table into something that will fit in fewer cachelines -- may or may not be a win..

The above uses the gcc/clang `a = __builtin_clzll(x)` intrinsic.  The MSVC equivalent of that is:
```
    unsigned long tmp;
    (void) _BitScanReverse64(&tmp, x);
    clz = 63 - tmp;
```
... the compiler will reduce that and eliminate `tmp` at the end, so don't let the `&tmp` scare you.

Anyway, maybe you've already tried something like this and didn't matter (I just watched the video of your talk, haven't read the paper yet) but maybe a couple nanoseconds could be shaved here.

As is usual this sort of code, the seminal reference material is Henry Warren's "Hacker's Delight"  If you have a copy of the Second Edition at hand (everyone should...) he discusses a number of log10 options in the last 6 pages of chapter 11.

**Comment by plokhotnyuk** [comment]
BTW, the Ryū routine call pow5Factor for `mm`:
https://github.com/ulfjack/ryu/blob/master/ryu/f2s.c#L219

So, just wonder, can that value be reused for `vplength` calculation?

**Comment by ulfjack** [comment]
Of course, I have a copy of Hacker's Delight. The log10 from HD (page 221) is slightly slower in my current benchmark, which repeats sample numbers iteration times, so the branches are all free (a shortcoming of my benchmark). When I change the benchmark to use a random set of numbers for each sample, the HD version is a tiny bit faster (46.887ns vs 47.499ns or so; it's pretty noisy).

I have a patch here: https://github.com/ulfjack/ryu/tree/log10-from-hackers-delight

I'm not sure if we should merge that or not.

**Comment by mitchblank** [comment]
@plokhotnyuk -- I don't know if `pow5Factor` would help, can you explain?  The problem there is that it's not computing log5(value) which might be useful for computing log10(value), it's just removing the bottom zeros from the base-5 representation.

@ulfjack -- unrelated, have you tried modifying `multipleOfPowerOf5()` to start with:
```
if (value % 2 == 0)
  return p == 0;
```
That adds a branch but means you can skip the loop entirely on half of the inputs, since even numbers won't be a multiple of any positive power of 5.

**Comment by mitchblank** [comment]
Actually playing with it a bit more (and playing with libdivide) it looks to me that `multipleOfPowerOf5()` should be implementable with a single branch and two integer multiplies:
```
struct test_div_by_pow5 {
	uint64_t pow5n;
	uint64_t magic;
	unsigned shift;
};

static const struct test_div_by_pow5 DIV_BY_POW5_TABLE[] = {
	{ 1, 0, 0 },
	/* magic/shift are the magic values created by libdivide_u64_branchfree_gen() */
	{               5, 0x999999999999999A, 2 }, /* 2^1 */
	{              25, 0x47AE147AE147AE15, 4 }, /* 2^2 */
	{             125, 0x0624DD2F1A9FBE77, 6 }, /* 2^3 */
	{             625, 0xA36E2EB1C432CA58, 9 }, /* 2^4 */
	{            3125, 0x4F8B588E368F0847, 11 }, /* 2^5 */
	{           15625, 0x0C6F7A0B5ED8D36C, 13 }, /* 2^6 */
	{           78125, 0xAD7F29ABCAF48579, 16 }, /* 2^7 */
	{          390625, 0x5798EE2308C39DFA, 18 }, /* 2^8 */
	{         1953125, 0x12E0BE826D694B2F, 20 }, /* 2^9 */
	{         9765625, 0xB7CDFD9D7BDBAB7E, 23 }, /* 2^10 */
	{        48828125, 0x5FD7FE17964955FE, 25 }, /* 2^11 */
	{       244140625, 0x19799812DEA11198, 27 }, /* 2^12 */
	{      1220703125, 0xC25C268497681C27, 30 }, /* 2^13 */
	{      6103515625, 0x6849B86A12B9B01F, 32 }, /* 2^14 */
	{     30517578125, 0x203AF9EE756159B3, 34 }, /* 2^15 */
	{    152587890625, 0xCD2B297D889BC2B7, 37 }, /* 2^16 */
	{    762939453125, 0x70EF54646D496893, 39 }, /* 2^17 */
	{   3814697265625, 0x2725DD1D243ABA0F, 41 }, /* 2^18 */
	{  19073486328125, 0xD83C94FB6D2AC34B, 44 }, /* 2^19 */
	{  95367431640625, 0x79CA10C9242235D6, 46 }, /* 2^20 */
	{ 476837158203125, 0x2E3B40A0E9B4F7DE, 48 }, /* 2^21 */
};

/* On input 0>=p>=21 */
static inline int multipleOfPowerOf5(const uint64_t value, const int32_t p) {
	if (p == 0) {
		/*
		 * Unfortunately there are no entries we can put in DIV_BY_POW5_TABLE[]
		 * that will "just work".  The only values where quotient*e->pow5n
		 * will always equal value for a constant "e" would be
		 *  quotient==value, e->pow5n==1
		 * this would imply (working backwards)
		 *  e->shift==0, t == value
		 *  value == value/2 + q/2
                 *  q=value*2
		 *  e->magic = 1<<65;
		 * So no value works
		 */
		return 1;
	}
	const struct test_div_by_pow5 *e = &DIV_BY_POW5_TABLE[p];
	/*
	 * First compute the same thing that libdivide_u64_branchfree_do()
	 * would have done.  I.e. these three lines are doing the same
	 * thing as...
	 *   const uint64_t quotient = value / e->pow5n;
	 * ...but we're avoiding a (very) expensive divide-by-variable.
	 */
	const uint64_t q = (uint64_t) ((((__uint128_t) value) * ((__uint128_t) e->magic)) >> 64);
	const uint64_t t = ((value - q) >> 1) + q;
	const uint64_t quotient = t >> e->shift;
	// Now test if it the division was exact.
	return quotient * e->pow5n == value;
}
```

As mentioned at the top, `p==0` seems hard to not make a special case (libdivide has this restriction for its "branchfree" variant, which we really want to use here, so that's not surprising.  Also I am using `__uint128_t` here; obviously this would have to be implemented portably like the other 128-bit math (but it's easier than the existing cases since we're only trying to get the high 64-bits)

The remaining question is whether the `p==0` case might be done better.  Near the callsite of this function you have a comment:
```
    // I tried special-casing q == 0, but there was no effect on performance.
```
(where `q` gets passed in and becomes `p` in `multipleOfPowerOf5()`)   So if you re-special-cased `q==0` then `multipleOfPowerOf5()` would just be concerning itself with p in the 1..21 range and could drop that branch.  In other words, we'd still have a branch for `q==0`, but since it will be taken in the caller function we can simplify more code there.

The other possibility is if `q==0` is rare it might be cheaper to let it do the multiplies and change the end of the function to say...
```
return quotient * e->pow5n == ((p == 0) ? ((uint64_t) 0) : value);
```
...since that will probably generate a `cmov` instead of a branch.

Anyway, I think that would be significantly faster than the `pow5Factor()` loop where we're doing a cosntant-divide and branch each time!

**Comment by ulfjack** [comment]
Oh, in addition - the loop that checks for pow5-ness only runs once in 4 out of 5 cases. It's increasingly unlikely for a random number to be a multiple of an increasing power of 5.

**Comment by mitchblank** [comment]
First, sorry about the dumb "check for even" suggestion; not sure what I was thinking there.

OK, I've actually broken out an instruction-level profiler so I can see where the hotspots really are.  I agree that it looks like on the random data that `benchmark` creates it isn't hot.  My remaining question there would be are there non-random (but common in practice) input values that can end up creating a highly-divisible input to `pow5Factor()`?  i.e. will its performance worst-case happen more often than random inputs would suggest?  I'm still getting my head around it.

One place that is very hot (as you know, I'm sure) is the digit-rendering at the end.  I have a question for you on that -- what is the possible range that `output` can have at that point.  My understanding is that it's always less than 10^17, correct?

If that's the case then the 32-bit code that is doing...
```
while ((output >> 32) != 0) {
```
...can be changed to an `if` since after one iteration through the loop `output` will be <10^8, so well within 32-bits.  In fact, if the input really is always <10^17 then you could use the `if()` to split the 64-bit case into two 32-bits parts that are either:
 * 1..9 digits, 8 digits     (i.e. by divmod'ing by 10^8)
 * 1..8 digits, 9 digits     (by divmoding by 10^9)
Right now you're doing the second option, but the first might be marginally cleaner since you have a bit less work inside the `if()`, since printing 8 digits requires one fewer divide.  However, if the actual range of the input goes up to 10^18 you can't use that trick, so I'd like to confirm that range first.

Best of all, this makes the 32-bit code work faster even on 64-bit processors!  This matches my prior experience that even on 64 bit Intel it's still cheaper to do 32-bit imul's.  Just by changing the `while()` to an `if()` and enabling that code saves about ~2ns/execution on my mac build.

**Comment by mitchblank** [comment]
For clarity, here's the change that assumes output<10^17:
```
diff --git a/ryu/d2s.c b/ryu/d2s.c
index a3f730b..933b6af 100644
--- a/ryu/d2s.c
+++ b/ryu/d2s.c
@@ -440,19 +440,18 @@ int d2s_buffered_n(double f, char* result) {
 #ifndef NO_DIGIT_TABLE
   // Print decimal digits after the decimal point.
   uint32_t i = 0;
-#if defined(_M_IX86) || defined(_M_ARM)
+#if 1 || defined(_M_IX86) || defined(_M_ARM)
   // 64-bit division is inefficient on 32-bit platforms.
   uint32_t output2;
-  while ((output >> 32) != 0) {
+  if ((output >> 32) != 0) {
     // Expensive 64-bit division.
-    output2 = (uint32_t) (output % 1000000000);
-    output /= 1000000000;
+    output2 = (uint32_t) (output % 100000000);
+    output /= 100000000;

     // Cheap 32-bit divisions.
     const uint32_t c = output2 % 10000;
     output2 /= 10000;
     const uint32_t d = output2 % 10000;
-    output2 /= 10000;
     const uint32_t c0 = (c % 100) << 1;
     const uint32_t c1 = (c / 100) << 1;
     const uint32_t d0 = (d % 100) << 1;
@@ -461,8 +460,7 @@ int d2s_buffered_n(double f, char* result) {
     memcpy(result + index + olength - i - 3, DIGIT_TABLE + c1, 2);
     memcpy(result + index + olength - i - 5, DIGIT_TABLE + d0, 2);
     memcpy(result + index + olength - i - 7, DIGIT_TABLE + d1, 2);
-    result[index + olength - i - 8] = (char) ('0' + output2);
-    i += 9;
+    i += 8;
   }
   output2 = (uint32_t) output;
 #else // ^^^ known 32-bit platforms ^^^ / vvv other platforms vvv
```
Starting from a completely virgin install, this seems to reliability shave >1ns from benchmark for me.

If it needs to work for output<10^18, this smaller change can be used.  Still faster than the original, but seems like about 0.5ns slower (although I didn't do enough iterations to be sure how accurate that is)
```
diff --git a/ryu/d2s.c b/ryu/d2s.c
index a3f730b..0baeb54 100644
--- a/ryu/d2s.c
+++ b/ryu/d2s.c
@@ -440,10 +440,10 @@ int d2s_buffered_n(double f, char* result) {
 #ifndef NO_DIGIT_TABLE
   // Print decimal digits after the decimal point.
   uint32_t i = 0;
-#if defined(_M_IX86) || defined(_M_ARM)
+#if 1 || defined(_M_IX86) || defined(_M_ARM)
   // 64-bit division is inefficient on 32-bit platforms.
   uint32_t output2;
-  while ((output >> 32) != 0) {
+  if ((output >> 32) != 0) {
     // Expensive 64-bit division.
     output2 = (uint32_t) (output % 1000000000);
     output /= 1000000000;
```

**Comment by ulfjack** [comment]
Thanks!

We have at most 17 digits in the worst case, but that's fine - an unsigned 32-bit int can hold 9. In the worst case, we start with 17, cut off 8, and are left with 9, which fits. I simplified the code, and see a small performance improvement. Maybe .5 ns on this MacBook Pro.

**Comment by mitchblank** [comment]
Excellent news.  Always exciting to save 500 picoseconds.

I saw that in your version of the change you switched the `(output >> 32) != 0` to `olength >= 8`  -- I see two issues with that:
1. doesn't it have to be `olength > 8`?  I don't think the code afterwards is prepared to emit zero bits, so we shouldn't run the the top half if we're not going to emit at least 9 digits
2. I suspect the `(output >> 32) != 0` was more optimal anyway, especially on 32-bit.  If the value is < 2^32 we can avoid the 64-bit divide entirely, so it's better to just use the lower-half code to emit the full value.  The `>>32==0` formulation should be pretty efficient too.

Was there a reason you made that change?

**Comment by ulfjack** [comment]
Doh! Thanks for the catch. Fixed.

It seemed simpler than the shift, but you're right that it might be slightly less optimal. Hmm.

**Comment by mitchblank** [comment]
I haven't looked at the assembly, but I don't think comparing `olength` is actually simpler anyway:
* on 64-bit, the shift will just be a `shr`/`je` pair.  No more expensive than a compare-with-immediate
* on 32-bit, it's even better: the `uint64_t` will be stored in a pair of registers, and a good compiler will be able to convert `x>>32==0` to `x_HI==0`, so it will just be testing one register directly.

It doesn't *really* matter either way since it only affects the rare case where output is >=10^9 and <2^32, but hey...

**Comment by ulfjack** [comment]
I think all the action items are done, so closing this. Thanks again!
