### ISSUE TITLE
d2s/f2s RYU_DEBUG inconsistency

### ISSUE THREAD

**Issue by StephanTLavavej** [ulfjack/ryu#47]
[d2s.c line 253](https://github.com/ulfjack/ryu/blob/e55d38383aa077a2ee5bae1fa9388a5962c37504/ryu/d2s.c#L253):

```
#ifdef RYU_DEBUG
  printf("E=%d M=%" PRIu64 "\n", e2 + 2, m2);
#endif
```

[f2s.c line 168](https://github.com/ulfjack/ryu/blob/e55d38383aa077a2ee5bae1fa9388a5962c37504/ryu/f2s.c#L168):

```
#ifdef RYU_DEBUG
  printf("E=%d M=%u\n", e2, m2);
#endif
```

`e2` and `m2` are computed in a structurally identical manner, so it seems inconsistent that d2s prints `e2 + 2` while f2s prints `e2`, but I don't know which one is desired.

**Comment by ulfjack** [comment]
It's probably better to print e2 + 2 because the original number is equal to m2*2^(e2+2). This is probably a holdover from when I did the - 2 as a separate step, and then I fixed it while debugging some 64-bit problems, but not for the 32-bit case.
