### ISSUE TITLE
RyuDouble.java tests against Float.POSITIVE_INFINITY, not Double.POSITIVE_INFINITY

### ISSUE THREAD

**Issue by LeeTibbert** [ulfjack/ryu#49]
Forgive me if there is something subtle going on that I have missed.
RyuDouble.java tests against Float.POSITIVE_INFINITY and its opposite.
I can understand RyuFloat.java doing that, but it seems mildly astonishing
in RyuDouble.java. I would expect to see the test against Double.POSITIVE_INFINITY
and its negation.

```
 public static String doubleToString(double value, RoundingMode roundingMode) {
    // Step 1: Decode the floating point number, and unify normalized and subnormal cases.
    // First, handle all the trivial cases.
    if (Double.isNaN(value)) return "NaN";
    if (value == Float.POSITIVE_INFINITY) return "Infinity";
    if (value == Float.NEGATIVE_INFINITY) return "-Infinity";
```

**Comment by cpplearner** [comment]
Double.POSITIVE_INFINITY == Float.POSITIVE_INFINITY

**Comment by LeeTibbert** [comment]
@cpplearner   
Thank you . I just twigged to that fact as I was working on another problem.
Technically correct, but seems like an unnecessary hoop to put a reader through.
Guess I am too used to strictly typed languages (and/or working too late at night.)

**Comment by ulfjack** [comment]
Not intentional. Let me fix this.
