### ISSUE TITLE
Suggest splitting into C and Java projects

### ISSUE THREAD

**Issue by ColinH** [ulfjack/ryu#53]
Title says it all, I'd like to suggest splitting into separate C and Java projects, so that things like issues and commits aren't all mixed together...

**Comment by StephanTLavavej** [comment]
As someone who's interested in only the C sources, I can say that Java commits don't affect me at all (they're like readme changes, in that they don't cause conflicts). It's also easy for me to ignore Java issues, so I have no desire for separate projects. However, I would suggest introducing C and Java labels for issues, so they can be easily filtered.

**Comment by plokhotnyuk** [comment]
Moreover I would suggest to sync with Java version as much as possible on common issues by opening paired issues to fix them in both versions of code and tests.

**Comment by ulfjack** [comment]
I added C and Java labels.

I'm not against splitting it up in principle, but I'm not convinced it's worth it at this time. As of this writing, we have 9 open issues, and there's only about one patch per day or so. I'm going to leave it as is for now. If we get a lot more issues filed / contributions, I'm happy to reconsider.
