### ISSUE TITLE
Missing carries in non-intrinsic umul128()?

### ISSUE THREAD

**Issue by StephanTLavavej** [ulfjack/ryu#94]
https://github.com/ulfjack/ryu/blob/2ec9ead2400afd7ff91a563fbc46ec62984fa3d0/ryu/d2s_intrinsics.h#L48-L76 implements a 64 * 64 = 128 wide multiplication. I realized that it implements the grade-school algorithm for multiplying two 2-digit numbers (where each "digit" is `uint32_t`), except that it's missing carries! This seems deeply concerning for correctness, but I haven't found any failures due to the missing carries yet.

Is there something about how Ryu calls `umul128()` that prevents this from being a problem? If so, should it be commented and/or asserted? My attempts to add carrying code have degraded x86 perf by at least 10%.

(I noticed that I replicated this behavior in `umul256()` so it has greater impact.)

**Comment by cpplearner** [comment]
The purpose of `b00Hi`, `mid1Hi`, `mid2Hi` is to handle carries, no?

**Comment by StephanTLavavej** [comment]
No. Those are decomposing 2-digit numbers into separate digits, not carrying after additions.

```
  67
* 89
——
  63 = 7 * 9
 56  = 7 * 8
 54  = 6 * 9
48   = 6 * 8
```

Now add columns of digits. The ones digit `3` is alone. The tens digits `6 + 6 + 4` sum to `16`, so the tens digit is `6` and we carry `1` into the hundreds. The hundreds are `1 + 5 + 5 + 8 = 19`, i.e. `9` and carrying `1`. The thousands digit is `1 + 4 = 5`. So `67 * 89 = 5963`.

This is exactly analogous to how this code should work. 1-digit numbers are `uint32_t`, 2-digit numbers are `uint64_t`, and they can be decomposed/recomposed with shifts. What’s missing are overflow checks during addition to propagate carries.

**Comment by StephanTLavavej** [comment]
Thank you! I'm glad I was jumping at phantoms.
